# This is so dirty! :/

# ggplot2 ----
# dput(ls("package:ggplot2"))
utils::globalVariables(c("%+%", "%+replace%", "aes", "aes_all", "aes_auto", "aes_q", 
                         "aes_string", "annotate", "annotation_custom", "annotation_logticks", 
                         "annotation_map", "annotation_raster", "autoplot", "benchplot", 
                         "borders", "calc_element", "continuous_scale", "coord", "coord_cartesian", 
                         "coord_equal", "coord_fixed", "coord_flip", "coord_map", "coord_polar", 
                         "coord_quickmap", "coord_trans", "cut_interval", "cut_number", 
                         "diamonds", "discrete_scale", "economics", "element_blank", "element_line", 
                         "element_rect", "element_text", "expand_limits", "facet", "facet_grid", 
                         "facet_null", "facet_wrap", "fortify", "geom_abline", "geom_area", 
                         "geom_bar", "geom_bin2d", "geom_blank", "geom_boxplot", "geom_contour", 
                         "geom_crossbar", "geom_density", "geom_density2d", "geom_dotplot", 
                         "geom_errorbar", "geom_errorbarh", "geom_freqpoly", "geom_hex", 
                         "geom_histogram", "geom_hline", "geom_jitter", "geom_line", "geom_linerange", 
                         "geom_map", "geom_path", "geom_point", "geom_pointrange", "geom_polygon", 
                         "geom_quantile", "geom_raster", "geom_rect", "geom_ribbon", "geom_rug", 
                         "geom_segment", "geom_smooth", "geom_step", "geom_text", "geom_tile", 
                         "geom_violin", "geom_vline", "gg_dep", "ggfluctuation", "ggmissing", 
                         "ggorder", "ggpcp", "ggplot", "ggplot_build", "ggplot_gtable", 
                         "ggplotGrob", "ggsave", "ggstructure", "ggtitle", "guide_colorbar", 
                         "guide_colourbar", "guide_legend", "guides", "is.coord", "is.facet", 
                         "is.ggplot", "is.theme", "label_both", "label_bquote", "label_parsed", 
                         "label_value", "label_wrap_gen", "labeller", "labs", "last_plot", 
                         "layer", "map_data", "mean_cl_boot", "mean_cl_normal", "mean_sdl", 
                         "mean_se", "median_hilow", "midwest", "movies", "mpg", "msleep", 
                         "opts", "plotmatrix", "position_dodge", "position_fill", "position_identity", 
                         "position_jitter", "position_jitterdodge", "position_stack", 
                         "presidential", "qplot", "quickplot", "rel", "resolution", "scale_alpha", 
                         "scale_alpha_continuous", "scale_alpha_discrete", "scale_alpha_identity", 
                         "scale_alpha_manual", "scale_area", "scale_color_brewer", "scale_color_continuous", 
                         "scale_color_discrete", "scale_color_distiller", "scale_color_gradient", 
                         "scale_color_gradient2", "scale_color_gradientn", "scale_color_grey", 
                         "scale_color_hue", "scale_color_identity", "scale_color_manual", 
                         "scale_colour_brewer", "scale_colour_continuous", "scale_colour_discrete", 
                         "scale_colour_distiller", "scale_colour_gradient", "scale_colour_gradient2", 
                         "scale_colour_gradientn", "scale_colour_grey", "scale_colour_hue", 
                         "scale_colour_identity", "scale_colour_manual", "scale_fill_brewer", 
                         "scale_fill_continuous", "scale_fill_discrete", "scale_fill_distiller", 
                         "scale_fill_gradient", "scale_fill_gradient2", "scale_fill_gradientn", 
                         "scale_fill_grey", "scale_fill_hue", "scale_fill_identity", "scale_fill_manual", 
                         "scale_linetype", "scale_linetype_continuous", "scale_linetype_discrete", 
                         "scale_linetype_identity", "scale_linetype_manual", "scale_shape", 
                         "scale_shape_continuous", "scale_shape_discrete", "scale_shape_identity", 
                         "scale_shape_manual", "scale_size", "scale_size_area", "scale_size_continuous", 
                         "scale_size_discrete", "scale_size_identity", "scale_size_manual", 
                         "scale_x_continuous", "scale_x_date", "scale_x_datetime", "scale_x_discrete", 
                         "scale_x_log10", "scale_x_reverse", "scale_x_sqrt", "scale_y_continuous", 
                         "scale_y_date", "scale_y_datetime", "scale_y_discrete", "scale_y_log10", 
                         "scale_y_reverse", "scale_y_sqrt", "seals", "should_stop", "stat_abline", 
                         "stat_bin", "stat_bin2d", "stat_bindot", "stat_binhex", "stat_boxplot", 
                         "stat_contour", "stat_density", "stat_density2d", "stat_ecdf", 
                         "stat_ellipse", "stat_function", "stat_hline", "stat_identity", 
                         "stat_qq", "stat_quantile", "stat_smooth", "stat_spoke", "stat_sum", 
                         "stat_summary", "stat_summary_hex", "stat_summary2d", "stat_unique", 
                         "stat_vline", "stat_ydensity", "theme", "theme_blank", "theme_bw", 
                         "theme_classic", "theme_get", "theme_gray", "theme_grey", "theme_light", 
                         "theme_line", "theme_linedraw", "theme_minimal", "theme_rect", 
                         "theme_segment", "theme_set", "theme_text", "theme_update", "update_element", 
                         "update_geom_defaults", "update_labels", "update_stat_defaults", 
                         "waiver", "xlab", "xlim", "ylab", "ylim"))

# ROCR ----
# dput(ls("package:ROCR"))
utils::globalVariables(c("performance", "plot", "prediction"))

# scales ----
# dput(ls("package:scales"))
utils::globalVariables(c("abs_area", "alpha", "area_pal", "as.trans", "asn_trans", "atanh_trans", 
                         "boxcox_trans", "brewer_pal", "cbreaks", "censor", "col_bin", 
                         "col_factor", "col_numeric", "col_quantile", "col2hcl", "colour_ramp", 
                         "comma", "comma_format", "ContinuousRange", "cscale", "date_breaks", 
                         "date_format", "date_trans", "dichromat_pal", "discard", "DiscreteRange", 
                         "div_gradient_pal", "dollar", "dollar_format", "dscale", "exp_trans", 
                         "expand_range", "extended_breaks", "format_format", "fullseq", 
                         "gradient_n_pal", "grey_pal", "hue_pal", "identity_pal", "identity_trans", 
                         "is.trans", "linetype_pal", "log_breaks", "log_trans", "log10_trans", 
                         "log1p_trans", "log2_trans", "logit_trans", "manual_pal", "math_format", 
                         "muted", "ordinal", "ordinal_format", "parse_format", "percent", 
                         "percent_format", "pretty_breaks", "probability_trans", "probit_trans", 
                         "reciprocal_trans", "rescale", "rescale_max", "rescale_mid", 
                         "rescale_none", "rescale_pal", "reverse_trans", "scientific", 
                         "scientific_format", "seq_gradient_pal", "shape_pal", "show_col", 
                         "sqrt_trans", "squish", "squish_infinite", "time_trans", "trans_breaks", 
                         "trans_format", "trans_new", "trans_range", "unit_format", "wrap_format", 
                         "zero_range"))

# dplyr ----
# dput(ls("package:dplyr"))
utils::globalVariables(c("%.%", "%>%", "add_rownames", "anti_join", "arrange", "arrange_", 
                         "as.tbl", "as.tbl_cube", "as_data_frame", "base_agg", "base_scalar", 
                         "base_win", "bench_tbls", "between", "bind_cols", "bind_rows", 
                         "build_sql", "chain", "chain_q", "changes", "collapse", "collect", 
                         "combine", "compare_tbls", "compute", "copy_lahman", "copy_nycflights13", 
                         "copy_to", "count", "count_", "cumall", "cumany", "cume_dist", 
                         "cummean", "data_frame", "data_frame_", "db_analyze", "db_begin", 
                         "db_commit", "db_create_index", "db_create_table", "db_data_type", 
                         "db_drop_table", "db_explain", "db_has_table", "db_insert_into", 
                         "db_list_tables", "db_query_fields", "db_query_rows", "db_rollback", 
                         "db_save_query", "dense_rank", "desc", "dim_desc", "distinct", 
                         "distinct_", "do", "do_", "escape", "eval_tbls", "explain", "failwith", 
                         "filter", "filter_", "first", "full_join", "funs", "funs_", "get_cluster", 
                         "glimpse", "group_by", "group_by_", "group_indices", "group_indices_", 
                         "group_size", "grouped_df", "grouped_dt", "groups", "has_cluster", 
                         "has_lahman", "id", "ident", "init_cluster", "inner_join", "intersect", 
                         "is.grouped_df", "is.grouped_dt", "is.ident", "is.sql", "is.src", 
                         "is.tbl", "knit_print.trunc_mat", "lahman_df", "lahman_dt", "lahman_mysql", 
                         "lahman_postgres", "lahman_sqlite", "lahman_srcs", "last", "lead", 
                         "left_join", "location", "make_tbl", "min_rank", "mutate", "mutate_", 
                         "mutate_each", "mutate_each_", "mutate_each_q", "n", "n_distinct", 
                         "n_groups", "nasa", "nth", "ntile", "nycflights13_postgres", 
                         "nycflights13_sqlite", "order_by", "partial_eval", "percent_rank", 
                         "progress_estimated", "query", "rbind_all", "rbind_list", "regroup", 
                         "rename", "rename_", "rename_vars", "rename_vars_", "right_join", 
                         "row_number", "rowwise", "same_src", "sample_frac", "sample_n", 
                         "select", "select_", "select_vars", "select_vars_", "semi_join", 
                         "set_cluster", "setdiff", "setequal", "show_query", "slice", 
                         "slice_", "sql", "sql_escape_ident", "sql_escape_string", "sql_infix", 
                         "sql_join", "sql_not_supported", "sql_prefix", "sql_quote", "sql_select", 
                         "sql_semi_join", "sql_set_op", "sql_subquery", "sql_translator", 
                         "sql_variant", "src", "src_desc", "src_df", "src_dt", "src_local", 
                         "src_mysql", "src_postgres", "src_sql", "src_sqlite", "src_tbls", 
                         "src_translate_env", "stop_cluster", "summarise", "summarise_", 
                         "summarise_each", "summarise_each_", "summarise_each_q", "summarize", 
                         "summarize_", "tally", "tbl", "tbl_cube", "tbl_df", "tbl_dt", 
                         "tbl_sql", "tbl_vars", "temp_srcs", "top_n", "translate_sql", 
                         "translate_sql_q", "transmute", "transmute_", "trunc_mat", "type_sum", 
                         "ungroup", "union", "with_order"))

# plyr ----
# dput(ls("package:plyr"))
utils::globalVariables(c("a_ply", "aaply", "adply", "alply", "amv_dimnames", "arrange", 
                         "as.quoted", "baseball", "catcolwise", "colwise", "compact", 
                         "count", "create_progress_bar", "d_ply", "daply", "ddply", "defaults", 
                         "desc", "dlply", "each", "empty", "eval.quoted", "failwith", 
                         "here", "id", "idata.frame", "is.discrete", "is.formula", "is.quoted", 
                         "isplit2", "join", "join.keys", "join_all", "l_ply", "laply", 
                         "ldply", "liply", "llply", "m_ply", "maply", "mapvalues", "match_df", 
                         "mdply", "mlply", "mutate", "name_rows", "numcolwise", "ozone", 
                         "progress_none", "progress_text", "progress_time", "progress_tk", 
                         "progress_win", "quickdf", "r_ply", "raply", "rbind.fill", "rbind.fill.matrix", 
                         "rdply", "rename", "revalue", "rlply", "round_any", "splat", 
                         "split_indices", "split_labels", "strip_splits", "summarise", 
                         "summarize", "take", "true", "try_default", "tryapply", "tryNULL", 
                         "unrowname", "vaggregate"))